[buildPlans.IosevkaKinderClear]
family = "Iosevka Kinder Clear"
spacing = "fixed"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

[buildPlans.IosevkaKinderClear.variants.design]
capital-g = "toothless-rounded-serifless-hooked"
capital-j = "serifless"
capital-k = "symmetric-touching-serifless"
capital-q = "crossing"
a = "double-storey-toothless-rounded"
b = "toothless-rounded-serifless"
d = "toothless-rounded-serifless"
f = "flat-hook-serifless"
g = "single-storey-flat-hook-earless-rounded"
i = "hooky"
j = "flat-hook-serifless"
k = "symmetric-touching-serifless"
l = "semi-tailed"
m = "earless-corner-double-arch-serifless"
n = "earless-rounded-straight-serifless"
p = "earless-rounded-serifless"
q = "earless-rounded-straight-serifless"
r = "earless-rounded-serifless"
t = "flat-hook"
u = "toothless-rounded-serifless"
y = "cursive-flat-hook-serifless"
long-s = "flat-hook-tailed-middle-serifed"
eszet = "sulzbacher-tailed-serifless"
lower-iota = "zshaped"
lower-lambda = "straight-turn"
lower-pi = "tailless"
lower-tau = "short-tailed"
lower-chi = "straight-motion-serifed"
cyrl-er = "earless-rounded-serifless"
cyrl-capital-u = "straight-turn-serifless"
cyrl-u = "straight-turn-serifless"
cyrl-yeri = "round"
cyrl-yery = "round"
cyrl-capital-ya = "standing-serifless"
cyrl-ya = "standing-serifless"
zero = "long-dotted"
one = "base"
two = "curly-neck-serifed"
three = "flat-top-serifed"
four = "closed-non-crossing-serifed"
five = "upright-flat-serifed"
six = "closed-contour"
seven = "bend-serifed"
eight = "two-circles"
nine = "closed-contour"
diacritic-dot = "square"
punctuation-dot = "square"
asterisk = "turn-penta-low"
underscore = "above-baseline"
paren = "flat-arc"
brace = "straight"
guillemet = "straight"
ampersand = "upper-open"
at = "threefold-tall"
cent = "open-cap"
percent = "rings-continuous-slash"
bar = "force-upright"
partial-derivative = "straight-bar"
lig-neq = "vertical-dotted"
lig-plus-chain = "with-notch"
lig-double-arrow-bar = "with-notch"
lig-single-arrow-bar = "with-notch"

[buildPlans.IosevkaKinderClear.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.IosevkaKinderClear.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.IosevkaKinderClear.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"